---
title: \large Predicting how climate change and short-term weather will affect terrestrial mammals' movement
author:
  - name: Stefano Mezzini
    email: stefano.mezzini@ubc.ca
    institute: [braes, biol]
  - name: Chris H. Fleming
    institute: [ucf, smith]
  - name: Kirk Safford
    institute: bcp
  - name: Michael J. Noonan
    email: michael.noonan@ubc.ca
    institute: [braes, biol, cmps]
institute:
  - braes: Okanagan Institute for Biodiversity, Resilience, and Ecosystem Services, The University of British Columbia Okanagan, Kelowna, British Columbia, Canada.
  - biol: Department of Biology, The University of British Columbia Okanagan, Kelowna, British Columbia, Canada.
  - ucf: Department of Biology, University of Central Florida, Orlando, Florida 32816, United States.
  - smith: Smithsonian Conservation Biology Institute, National Zoological Park, 1500 Remount Rd., Front Royal, VA 22630, United States.
  - bcp: BC Parks
  - cmps: Department of Computer Science, Math, Physics, and Statistics, The University of British Columbia Okanagan, Kelowna, British Columbia, Canada.
bibliography: 'refs.bib'
# csl: 'csl.csl'
fontsize: 12pt
indent: true
header-includes:
    - \usepackage{setspace}\doublespacing # for double-spaced text
    - \usepackage{indentfirst} # for indenting first line of each paragraph
    - \usepackage[small]{titlesec} # for smaller font for headings
    - \usepackage{caption} # for more customization of captions
    - \captionsetup[figure]{font=scriptsize, aboveskip=4pt, belowskip=-15pt}
    - \usepackage{hanging} # for hanging indents in references
subparagraph: true # needed for \usepackage[small]{titlesec}
output:
  bookdown::pdf_document2:
    pandoc_args:
      - '--lua-filter=scholarly-metadata.lua'
      - '--lua-filter=author-info-blocks.lua'
    toc: false
    number_sections: false
editor_options: 
  chunk_output_type: console
---

<!-- place table of contents on a new page -->
\newpage

\singlespacing

\tableofcontents

<!-- start main body on a new page -->
\newpage

\doublespacing

```{r setup, include=FALSE}
# set chunk defaults: don't print code, images 75% of page width and centered
knitr::opts_chunk$set(echo = FALSE, out.width = '\\textwidth',
                      fig.align = 'center')
```

# Abstract



# Introduction

<!-- - central question -->
How does temperature affect the movement rates of mammals in BC? How will mammals move differently in the next century in response to climate change?

<!-- - relevance of the question -->
Estimating the movement rates of mammals allows us to quantify: (1) changes in mammals' energetic expenditures due to changes in movement, (2) changes in human-wildlife conflict due to changes in activity rates.

<!-- - address any questions answered in the discussion -->


# Methods

<!-- - data needed -->
mammals' GPS location data, mammals' speeds, historical weather data, climate change projections

## Estimating mammals' instantaneous speeds

`1-compile-data.R` merges all telemetry data into a single tibble, which it saves as an rds file.
`2-movement-models.R` fits variograms, movement models, and utilization distributions.

Elk tracking data were obtained from Movebank [@kays_movebank_2022; study name: Elk in southwestern Alberta], while the boreal caribou and wolf data were obtained from a public BC Oil and Gas Research and Innovation Society repository ([https://www.bcogris.ca/projects/boreal-caribou-telemetry-data/](https://www.bcogris.ca/projects/boreal-caribou-telemetry-data/)). ***All other tracking data were obtained from private collaborators.***

Animal movement models were fit using the `ctmm` package [@fleming_ctmm_2021] for `R` [@r_core_team_r_2022] following the removal of outlier GPS locations, which were diagnosed using the plots generated by `ctmm`'s `outlie()` function. Mammals' speeds were then estimated using the `speeds()` function on all OUF models ***check if there are any non-OUF models with speed estiamtes in the dataset*** [@noonan_scale-insensitive_2019]. Since `ctmm`'s movement models assume animals to be continuously moving, speeds were set to zero if they were not significantly different from zero ($\alpha = 0.05$), under the assumption that speed followed a $\chi^2$ distribution. The function used is available on GitHub in the `functions` folder of the repository associated with this project ([https://github.com/QuantitativeEcologyLab/bc-mammals-speeds/blob/main/functions/detrend_speeds.R](https://github.com/QuantitativeEcologyLab/bc-mammals-speeds/blob/main/functions/detrend_speeds.R)).

## Weather and climate data

Rasters of hourly historical temperature, precipitation and snow depth data was downloaded from the European Center for Medium-range Weather Forecasting (ECMWF; [www.ecmwf.int](www.ecmwf.int)) using the `ecmwfr` package for `R` [@hufkens_ecwmfr_2019]. Proximal weather conditions were then estimated by extracting the values from the nearest raster cell to each GPS location using the `exact_extract()` function from the `XXX` package [@ref].

Projections of monthly temperature and precipitation in BC during the next 80 years were downloaded via the ClimateNA software [@ref] using the `climatenaR` package [@burnett_climatenar_2023]. The climate projections were used... since snow was not available ***HERE***

# add weather data to tels
`add-speeds-and-weather.R`

# fit models
`weather-regressions.R`

# predictions for the region
`download-dem.R`
`download-climate-projections.R`
>>> **should predict for the area the animals are in only**
> script for figures

# predictions for BC
`download-bc-dem.R`
`download-bc-climate-projections.R`
`bind-climate-change-predictions.R`
  `check-species-ranges.R`
> script for figures



# Results

<!-- - show main trends -->

# Discussion

<!-- - how results answer central question -->


<!-- - what it tells us about the broader field -->


<!-- - address any questions presented in the discussion -->


\clearpage <!-- to prevent figures from floating to the references -->

\newpage <!-- place references on a separate page -->

# References

\hangparas{1em}{1} <!-- paragraphs hanging by width equal to font height -->
